Web-HW10/hw_project/hw_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quotes.urls")),
    path("users/", include("users.urls"))
]

Web-HW10/hw_project/quotes/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "quotes"

urlpatterns = [
    path("", views.main, name="main"),
    path("<int:page>", views.main, name="root_paginate"),
    path('tag/', views.tag, name='tag'),
    path('note/', views.note, name='note'),


]

Web-HW10/hw_project/users/urls.py
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

Web-HW10/hw_project/quotes/models.py
from django.db import models


# Create your models here.

class Author(models.Model):
    fullname = models.CharField(max_length=50)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=150)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)


class Tag(models.Model):
    objects = None
    name = models.CharField(max_length=30, null=False, unique=True)


class Note(models.Model):
    objects = None
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

Web-HW10/hw_project/users/models.py
from django.db import models

# Create your models here.

Web-HW10/hw_project/quotes/forms.py
from django.forms import ModelForm, CharField, TextInput
from .models import Tag, Quote


class TagForm(ModelForm):
    name = CharField(min_length=3, max_length=25, required=True, widget=TextInput())

    class Meta:
        model = Tag
        fields = ['name']


class NoteForm(ModelForm):

    name = CharField(min_length=5, max_length=50, required=True, widget=TextInput())
    description = CharField(min_length=10, max_length=150, required=True, widget=TextInput())

    class Meta:
        model = Note
        fields = ['name', 'description']
        exclude = ['tags']

Web-HW10/hw_project/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

from .models import Profile


class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput())

    email = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput())

    password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())

    password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class LoginForm(AuthenticationForm):

    class Meta:
        model = User
        fields = ['username', 'password']


class ProfileForm(forms.ModelForm):
    avatar = forms.ImageField(widget=forms.FileInput())

    class Meta:
        model = Profile
        fields = ['avatar']

Web-HW10/hw_project/quotes/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_object_or_404

from .forms import TagForm, NoteForm
from .models import Tag, Quote


# Create your views here.
def main(request, page=1):
    quotes = Quote.objects.all().order_by('id')
    per_page = 10
    paginator = Paginator(quotes, per_page)
    quotes_on_page = paginator.page(page)

    return render(request, "quotes/index.html", context={"quotes": quotes_on_page, 'paginator': paginator})


@login_required
def tag(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            tag = form.save(commit=False)
            tag.user = request.user
            tag.save()
            return redirect(to='quotes:main')
        else:
            return render(request, 'quotes/tag.html', {'form': form})

    return render(request, 'quotes/tag.html', {'form': TagForm()})


@login_required
def note(request):
    tags = Tag.objects.all()

    if request.method == 'POST':
        form = NoteForm(request.POST)
        if form.is_valid():
            new_note = form.save()

            choice_tags = Tag.objects.filter(name__in=request.POST.getlist('tags'))
            for tag in choice_tags.iterator():
                new_note.tags.add(tag)

            return redirect(to='quotes:main')
        else:
            return render(request, 'quotes/note.html', {"tags": tags, 'form': form})

    return render(request, 'quotes/note.html', {"tags": tags, 'form': NoteForm()})

Web-HW10/hw_project/users/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from .forms import RegisterForm, LoginForm



def signupuser(request):
    if request.user.is_authenticated:
        return redirect(to='quotes:main')

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotes:main')
        else:
            return render(request, 'users/signup.html', context={"form": form})

    return render(request, 'users/signup.html', context={"form": RegisterForm()})


def loginuser(request):
    if request.user.is_authenticated:
        return redirect(to='quotes:main')

    if request.method == 'POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is None:
            messages.error(request, 'Username or password didn\'t match')
            return redirect(to='users:login')

        login(request, user)
        return redirect(to='quotes:main')

    return render(request, 'users/login.html', context={"form": LoginForm()})


@login_required
def logoutuser(request):
    logout(request)
    return redirect(to='quotes:main')

class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    html_email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('users:password_reset_done')
    success_message = "An email with instructions to reset your password has been sent to %(email)s."
    subject_template_name = 'users/password_reset_subject.txt'

Web-HW10/hw_project/quotes/templates/quotes/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
    <title>Homework</title>
</head>
<body>
<div class="container">
    <div class="row header-box pt-3 mb-3">
        <div class="col-md-8">
            <h1>
                <a href="/" style="text-decoration: none">Quotes to Scrape</a>
            </h1>
        </div>
        <div class="col-md-4">
            <p>
                <a href="{% url 'users:logout' %}" class="btn btn-primary">Logout</a>
                <a href="{% url 'users:login' %}" class="btn btn-primary">Login</a>
                <a href="{% url 'users:signup' %}" class="btn btn-primary">SignUp</a>
            </p>
        </div>
    </div>

{% block content %} {% endblock %}


</div>


</body>
</html>

Web-HW10/hw_project/quotes/templates/quotes/index.html
{% extends "quotes/base.html" %}
{% load extract %}

{% block content %}

<nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
    {% if user.is_authenticated %}
    <ul>
        <li>Welcome <b>{{ user.username }}!</b></li>
        <li><a href="{% url 'quotes:tag' %}" role="button">Add tag</a></li>
        <li><a href="{% url 'quotes:note' %}" role="button">Add note</a></li>
    </ul>
    {% else %}
<!--    <ul>-->
<!--        <li><a href="{% url 'users:signup' %}" role="button">Sign Up</a></li>-->
<!--        <li><a href="{% url 'users:login' %}" role="button">Login</a></li>-->
<!--    </ul>-->
    {% endif %}
</nav>

<div class="row">
    <div class="col-md-8">
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">
                {{quote.quote}}
            </span>
            <span>by <small class="author" itemprop="author">{{quote.author.fullname}}</small>
        <a href="/author/{{quote.author}}">(about)</a>
        </span>
            <div class="tags">
                Tags:
                {% for tag in quote.tags.all %}

                <a class="tag" href="/tag/{{tag}}">{{tag}}</a>
                {% endfor %}

            </div>
        </div>

        {% endfor %}
        <nav>
            <ul class="pager">

                <li class="previous">
                    <a class="{% if not quotes.has_previous %} disabled {% endif %}"
                       href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
                        <span aria-hidden="true">←</span> Previous
                    </a>
                </li>


                <li class="next">
                    <a class="{% if not quotes.has_next %} disabled {% endif %}"
                       href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">Next <span aria-hidden="true">→</span></a>
                </li>

            </ul>
        </nav>
    </div>

</div>

{% endblock %}

Web-HW10/hw_project/quotes/templates/quotes/note.html
{% extends "quotes/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotes:note' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Note name:
            {{ form.name }}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div style="padding: 10px">
        <label> Note description:
            {{ form.description }}
        </label>
        <span>{{ form.errors.description }}</span>
    </div>
    <div style="padding: 10px">
        <label> Select tags:
            <select name="tags" multiple="multiple" required>
                {% for tag in tags %}
                <option value="{{tag.name}}">{{tag.name}}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>
{% endblock %}

Web-HW10/hw_project/quotes/templates/quotes/tag.html
{% extends "quotes/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotes:tag' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the tag name:
            {{form.name}}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

Web-HW10/hw_project/users/templates/users/login.html
{% extends "noteapp/base.html" %}

{% block content %}

{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

<form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
    </div>

    <div>
        <label>Password:
            {{ form.password }}
        </label>
    </div>

    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
    <div class="small text-center">
        <a href="{% url "users:password_reset" %}" class="text-center"><i>Forgot Password?</i></a>
    </div>
</form>

{% endblock %}

Web-HW10/hw_project/users/templates/users/password_reset.html
{% extends "noteapp/base.html" %}

{% block content %}

<h2>Password reset</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Request password reset</button>
</form>

{% endblock %}

Web-HW10/hw_project/users/templates/users/password_reset_complete.html
{% extends "noteapp/base.html" %}

{% block content %}

    <h2>Password reset complete!</h2>

{% endblock %}

Web-HW10/hw_project/users/templates/users/password_reset_confirm.html
{% extends "noteapp/base.html" %}

{% block content %}

<h2>Enter new password</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save new password</button>
</form>

{% endblock %}

Web-HW10/hw_project/users/templates/users/password_reset_done.html
{% extends "noteapp/base.html" %}

{% block content %}

<h2>Password reset request sent</h2>
<p>We've emailed you with instructions on how to reset your password.</p>

{% endblock %}

Web-HW10/hw_project/users/templates/users/password_reset_email.html
{% autoescape off %}
<body>
<p>Hi {{ user.username }},</p>
<p>You requested a password reset for your account. Please follow this link to set a new password:</p>
<p>
    <a href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">
        {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
    </a>
</p>
<p>If you didn't request a password reset, please ignore this email.</p>
<p>Thanks,</p>
<p>The Our Team</p>
{% endautoescape %}

Web-HW10/hw_project/users/templates/users/profile.html
{% extends "noteapp/base.html" %}

{% block content %}
<div>
    <h1>Profile page: {{user.username}}</h1>
    <img src="{{ user.profile.avatar.url }}" alt="avatar of user"/>
</div>

{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-row">
        <div class="col-md-5">
            <div class="form-group">
                <label class="small mb-1">Change Avatar:</label>
                {{ profile_form.avatar }}
                <span>{{ profile_form.errors.avatar }}</span>
            </div>
        </div>
    </div>
    <div class="grid">
        <button type="submit">Save Changes</button>
        <button type="reset" class="secondary">Reset</button>
    </div>

</form>

{% endblock content %}

Web-HW10/hw_project/users/templates/users/signup.html
{% extends "noteapp/base.html" %}

{% block content %}

<div>
    <h2>Sign Up</h2>
</div>

<form method="post" action="{% url 'users:signup' %}">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
        <span>{{ form.errors.username }}</span>
    </div>
    <div>
        <label> Email:
            {{ form.email }}
        </label>
        <span>{{ form.errors.email }}</span>
    </div>
    <div>
        <label> Password:
            {{ form.password1 }}
        </label>
        <span>{{ form.errors.password1 }}</span>
    </div>
    <div>
        <label> Password confirmation:
            {{ form.password2 }}
        </label>
        <span>{{ form.errors.password2 }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}